services:
  - docker
jobs:
  include:
    - stage: build
      language: minimal
      script:
        - docker build . -t shu-zhi-net-backend
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag shu-zhi-net-backend $DOCKER_USERNAME/shu-zhi-net-backend
        - docker push $DOCKER_USERNAME/shu-zhi-net-backend